// <auto-generated />
using System;
using FinTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221115946_AddTransferCategory")]
    partial class AddTransferCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FinTrack.Core.Models.BudgetLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("BudgetLimits");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Maaş",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ek Gelir/Serbest",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Market & Mutfak",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kira",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Faturalar",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eğlence",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kişisel Harçlık",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Çocuk Harçlığı",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Taze Gıda & Pazar",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aile Harcamaları",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ulaşım",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ev & Yaşam",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Giyim",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Eğitim",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sağlık",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hediye & Bağış",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Yemek Ödeneği",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Aile Desteği",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kredi Kartı Çekilen",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ekstra Ödemesi",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kredi Kartı Ödemesi",
                            Type = 2
                        });
                });

            modelBuilder.Entity("FinTrack.Core.Models.CreditCardAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CreditCardAccounts");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InflationCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpiRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("InflationCaches");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreditCardAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreditCardAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Models.BudgetLimit", b =>
                {
                    b.HasOne("FinTrack.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Transaction", b =>
                {
                    b.HasOne("FinTrack.Core.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTrack.Core.Models.CreditCardAccount", "CreditCardAccount")
                        .WithMany()
                        .HasForeignKey("CreditCardAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CreditCardAccount");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
