// <auto-generated />
using System;
using FinTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308072104_AddInstallmentGroupId")]
    partial class AddInstallmentGroupId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FinTrack.Core.Models.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("FinTrack.Core.Models.BudgetLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("BudgetLimits");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Maaş",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ek Gelir/Serbest",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Market & Mutfak",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kira",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Faturalar",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eğlence",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kişisel Harçlık",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Çocuk Harçlığı",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Taze Gıda & Pazar",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aile Harcamaları",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ulaşım",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ev & Yaşam",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Giyim",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Eğitim",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sağlık",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hediye & Bağış",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Yemek Ödeneği",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Aile Desteği",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kredi Kartı Çekilen",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ekstra Ödemesi",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kredi Kartı Ödemesi",
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Elektrik",
                            ParentCategoryId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Su",
                            ParentCategoryId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Doğalgaz",
                            ParentCategoryId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "İnternet & TV",
                            ParentCategoryId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "Telefon",
                            ParentCategoryId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Aidat",
                            ParentCategoryId = 5,
                            Type = 1
                        });
                });

            modelBuilder.Entity("FinTrack.Core.Models.CreditCardAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Limit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCardId");

                    b.ToTable("CreditCardAccounts");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InflationCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpiRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("InflationCaches");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InvestmentAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvestmentAssets");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InvestmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestmentAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedBankAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedCreditCardAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentAssetId");

                    b.HasIndex("LinkedBankAccountId");

                    b.HasIndex("LinkedCreditCardAccountId");

                    b.ToTable("InvestmentTransactions");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreditCardAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreditCardAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Models.BudgetLimit", b =>
                {
                    b.HasOne("FinTrack.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Category", b =>
                {
                    b.HasOne("FinTrack.Core.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FinTrack.Core.Models.CreditCardAccount", b =>
                {
                    b.HasOne("FinTrack.Core.Models.CreditCardAccount", "ParentCard")
                        .WithMany("LinkedCards")
                        .HasForeignKey("ParentCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentCard");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InvestmentTransaction", b =>
                {
                    b.HasOne("FinTrack.Core.Models.InvestmentAsset", "InvestmentAsset")
                        .WithMany("Transactions")
                        .HasForeignKey("InvestmentAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTrack.Core.Models.BankAccount", "LinkedBankAccount")
                        .WithMany()
                        .HasForeignKey("LinkedBankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinTrack.Core.Models.CreditCardAccount", "LinkedCreditCardAccount")
                        .WithMany()
                        .HasForeignKey("LinkedCreditCardAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InvestmentAsset");

                    b.Navigation("LinkedBankAccount");

                    b.Navigation("LinkedCreditCardAccount");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Transaction", b =>
                {
                    b.HasOne("FinTrack.Core.Models.BankAccount", "BankAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinTrack.Core.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTrack.Core.Models.CreditCardAccount", "CreditCardAccount")
                        .WithMany()
                        .HasForeignKey("CreditCardAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankAccount");

                    b.Navigation("Category");

                    b.Navigation("CreditCardAccount");
                });

            modelBuilder.Entity("FinTrack.Core.Models.BankAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Models.Category", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTrack.Core.Models.CreditCardAccount", b =>
                {
                    b.Navigation("LinkedCards");
                });

            modelBuilder.Entity("FinTrack.Core.Models.InvestmentAsset", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
